### ISSUE TITLE
The project has critical & high vulnerabilities in the dependencies

### ISSUE THREAD

**Issue by FOSSAware** [open-amdocs/webrix-docs#34]
I found known published vulnerabilities in the following dependencies:
Merge, cryptiles, handlebars, elliptic, lodash, content, fresh, hapi, hoek, is-svg, merge-deep, moment, node-forge, ssri, node-uuid, websocket-extensions, yargs-parser

please choose clean versions, there are too many...

**Comment by ykadosh** [comment]
Hi, thanks for notifying.
None of the above are in our dependency list. These are sub-dependencies.
Can you share where these vulnerabilities are documented?
Any suggestion how we can fix this?

**Comment by FOSSAware** [comment]
Hi Yoav,
Although these are transitive dependencies of a direct dependencies that you are using. You should have a complete risk review of the product after the build. I ran it with software composition analysis tool and got these open source components reported as vulnerable.
Do you have such tool as well?

Zvika

Zvika Ronen via Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ykadosh** [comment]
Yes, we do, it's called `npm audit`,  but it reported far fewer results than what you reported.
This is why I asked where these vulnerabilities have been reported.

**Comment by FOSSAware** [comment]
The vulnerabilities were reported on the Snyk tool.
I suggest checking with pormal tool and not only with the npm audit.


Zvika Ronen
Chief Technology Officer (CTO)
Tel: +972-52-426-5306 (Mobile)
***@***.***D74209.4A35D5E0]
www.fossaware.com<http://www.fossaware.com>
“The greatest risk is the one you are not aware of”

**Comment by ykadosh** [comment]
Thanks for reporting Zvika, we will look into it 👍
